version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - microservices-network

  auth-service:
    build:
      context: ./auth-services
      dockerfile: Dockerfile
    container_name: auth-services
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  # product-service:
  #   build:
  #     context: ./product-service
  #     dockerfile: Dockerfile
  #   container_name: product-service
  #   ports:
  #     - "8082:8080"
  #   networks:
  #     - microservices-network
  #   environment:
  #     - DATABASE_URL=jdbc:mysql://db:3306/mydatabase

  # order-service:
  #   build:
  #     context: ./order-service
  #     dockerfile: Dockerfile
  #   container_name: order-service
  #   ports:
  #     - "8083:8080"
  #   networks:
  #     - microservices-network
  #   environment:
  #     - DATABASE_URL=jdbc:mysql://db:3306/mydatabase

  # additional-service:
  #   build:
  #     context: ./additional-service
  #     dockerfile: Dockerfile
  #   container_name: additional-service
  #   ports:
  #     - "8084:8080"
  #   networks:
  #     - microservices-network
  #   environment:
  #     - DATABASE_URL=jdbc:mysql://db:3306/mydatabase

  nextjs-front:
    build:
      context: ./sport-store-app
      dockerfile: Dockerfile
    container_name: nextjs-front
    ports:
      - "3000:3000"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  db-data:

